export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL || 'https://mentalwealthacademy.world';
  
  return Response.json({
    accountAssociation: {
      header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4ODE0QWIzYWUzQTRFMDdGMUUxM2IzOUY2Y2Q5YUViRDUzYzQ4QUQ3OSJ9",
      payload: "eyJkb21haW4iOiJtZW50YWx3ZWFsdGhhY2FkZW15LndvcmxkIn0",
      signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAC6XtDGqoxJA4-Bnlh-JjPEqfQooAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQP3Cpp8LH1fN_u1d5PWYmnDtmzvAqlN5LIOjBE-Z7m1QWGg350MezRUJUW9min8xULKVJhvkqocU4D4XA-x2KjfhWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABS62apD4lC4T0RXqNjlZvUwgiDvQyxALnaU4mloyjAIl1Mov85xdvL4MIE3q-AAUjh-po1Uz3o2pzihLNC0SPDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiZlJDRmsxQ2haYjVCbXBOZ2l0TXdhclVKMG5mVF9mNkdxdDF4NU16TG5rVSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS"
    },
    miniapp: {
      version: "1",
      name: "Mental Wealth Academy",
      homeUrl: URL,
      iconUrl: `${URL}/icons/mentalwealth-academy-logo.png`,
      splashImageUrl: `${URL}/icons/embbedBanner.png`,
      splashBackgroundColor: "#000000",
      webhookUrl: `${URL}/api/webhook`,
      subtitle: "Next Gen Micro-University",
      description: "Mental Wealth Academy is a virtual learning platform for the next generation. Learn, complete quests, earn rewards on-chain.",
      screenshotUrls: [
        `${URL}/icons/embbedBanner.png`
      ],
      primaryCategory: "education",
      tags: ["education", "learning", "blockchain", "web3", "academy"],
      heroImageUrl: `${URL}/icons/embbedBanner.png`,
      tagline: "Learn & Earn Together",
      ogTitle: "Mental Wealth Academy",
      ogDescription: "Virtual learning platform for the next generation with blockchain rewards",
      ogImageUrl: `${URL}/icons/embbedBanner.png`,
      noindex: false
    }
  });
}
